<?php 
_uge("General Settings","revslider"); 
_uge("Position","revslider"); 
_uge("Appearance","revslider"); 
_uge("Navigation","revslider"); 
_uge("Thumbnails","revslider"); 
_uge("Mobile Visibility","revslider"); 
_uge("Alternative First Slide","revslider"); 
_uge("Troubleshooting","revslider"); 
_uge("Delay","revslider"); 
_uge("The time one slide stays on the screen in Milliseconds","revslider"); 
_uge("Shuffle Mode","revslider"); 
_uge("Turn Shuffle Mode on and off! Will be randomized only once at the start.","revslider"); 
_uge("On","revslider"); 
_uge("Off","revslider"); 
_uge("Lazy Load","revslider"); 
_uge("The lazy load means that the images will be loaded by demand, it speeds the loading of the slider.","revslider"); 
_uge("Load Google Font","revslider"); 
_uge("yes / no to load google font","revslider"); 
_uge("Yes","revslider"); 
_uge("No","revslider"); 
_uge("Google Font","revslider"); 
_uge("The google font family to load","revslider"); 
_uge("To add more google fonts please read <a target=\"_blank\" href=\"http://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380/faqs/15268\"> this tutorial </a> ","revslider"); 
_uge("Stop Slider","revslider"); 
_uge("On / Off to stop slider after some amount of loops / slides","revslider"); 
_uge("Stop After Loops","revslider"); 
_uge("Stop the slider after certain amount of loops. 0 related to the first loop.","revslider"); 
_uge("Stop At Slide","revslider"); 
_uge("Stop the slider at the given slide","revslider"); 
_uge("Position on the page","revslider"); 
_uge("The position of the slider on the page, (float:left, float:right, margin:0px auto;)","revslider"); 
_uge("Left","revslider"); 
_uge("Center","revslider"); 
_uge("Right","revslider"); 
_uge("Margin Top","revslider"); 
_uge("The top margin of the slider wrapper div","revslider"); 
_uge("px","revslider"); 
_uge("Margin Bottom","revslider"); 
_uge("The bottom margin of the slider wrapper div","revslider"); 
_uge("Margin Left","revslider"); 
_uge("The left margin of the slider wrapper div","revslider"); 
_uge("Margin Right","revslider"); 
_uge("The right margin of the slider wrapper div","revslider"); 
_uge("Shadow Type","revslider"); 
_uge("The Shadow display underneath the banner. The shadow apply to fixed and responsive modes only, the full width slider don't have a shadow.","revslider"); 
_uge("No Shadow","revslider"); 
_uge("1","revslider"); 
_uge("2","revslider"); 
_uge("3","revslider"); 
_uge("Show Timer Line","revslider"); 
_uge("Show the top running timer line","revslider"); 
_uge("Top","revslider"); 
_uge("Bottom","revslider"); 
_uge("Hide","revslider"); 
_uge("Background color","revslider"); 
_uge("Slider wrapper div background color, for transparent slider, leave empty.","revslider"); 
_uge("Padding (border)","revslider"); 
_uge("The wrapper div padding, if it has value, then together with background color it it will make border around the slider.","revslider"); 
_uge("Show Background Image","revslider"); 
_uge("yes / no to put background image to the main slider wrapper.","revslider"); 
_uge("Background Image Url","revslider"); 
_uge("The background image that will be on the slider wrapper. Will be shown at slider preloading.","revslider"); 
_uge("Touch Enabled","revslider"); 
_uge("Enable Swipe Function on touch devices","revslider"); 
_uge("Stop On Hover","revslider"); 
_uge("Stop the Timer when hovering the slider","revslider"); 
_uge("Navigation Type","revslider"); 
_uge("Display type of the navigation bar (Default:none","revslider"); 
_uge("None","revslider"); 
_uge("Bullet","revslider"); 
_uge("Thumb","revslider"); 
_uge("Both","revslider"); 
_uge("Navigation Arrows","revslider"); 
_uge("Display position of the Navigation Arrows (** By navigation Type Thumb arrows always centered or none visible)","revslider"); 
_uge("With Bullets","revslider"); 
_uge("Solo","revslider"); 
_uge("Navigation Style","revslider"); 
_uge("Look of the navigation bullets  ** If you choose navbar, we recommend to choose Navigation Arrows to nexttobullets","revslider"); 
_uge("Round","revslider"); 
_uge("Navbar","revslider"); 
_uge("Old Round","revslider"); 
_uge("Old Square","revslider"); 
_uge("Old Navbar","revslider"); 
_uge("Always Show Navigation","revslider"); 
_uge("Always show the navigation and the thumbnails.","revslider"); 
_uge("Hide Navitagion After","revslider"); 
_uge("Time after that the Navigation and the Thumbs will be hidden(Default: 200 ms)","revslider"); 
_uge("ms","revslider"); 
_uge("Navigation Horizontal Align","revslider"); 
_uge("Horizontal Align of Bullets / Thumbnails","revslider"); 
_uge("Navigation Vertical Align","revslider"); 
_uge("Vertical Align of Bullets / Thumbnails","revslider"); 
_uge("Navigation Horizontal Offset","revslider"); 
_uge("Offset from current Horizontal position of Bullets / Thumbnails negative and positive direction","revslider"); 
_uge("Navigation Vertical Offset","revslider"); 
_uge("Offset from current Vertical  position of Bullets / Thumbnails negative and positive direction","revslider"); 
_uge("Left Arrow Horizontal Align","revslider"); 
_uge("Horizontal Align of left Arrow (only if arrow is not next to bullets)","revslider"); 
_uge("Left Arrow Vertical Align","revslider"); 
_uge("Vertical Align of left Arrow (only if arrow is not next to bullets)","revslider"); 
_uge("Left Arrow Horizontal Offset","revslider"); 
_uge("Offset from current Horizontal position of of left Arrow  negative and positive direction","revslider"); 
_uge("Left Arrow Vertical Offset","revslider"); 
_uge("Offset from current Vertical position of of left Arrow negative and positive direction","revslider"); 
_uge("Right Arrow Horizontal Align","revslider"); 
_uge("Horizontal Align of right Arrow (only if arrow is not next to bullets)","revslider"); 
_uge("Right Arrow Vertical Align","revslider"); 
_uge("Vertical Align of right Arrow (only if arrow is not next to bullets)","revslider"); 
_uge("Right Arrow Horizontal Offset","revslider"); 
_uge("Offset from current Horizontal position of of right Arrow negative and positive direction","revslider"); 
_uge("Right Arrow Vertical Offset","revslider"); 
_uge("Offset from current Vertical position of of right Arrow negative and positive direction","revslider"); 
_uge("Thumb Width","revslider"); 
_uge("The basic Width of one Thumbnail (only if thumb is selected)","revslider"); 
_uge("Thumb Height","revslider"); 
_uge("the basic Height of one Thumbnail (only if thumb is selected)","revslider"); 
_uge("Thumb Amount","revslider"); 
_uge("the amount of the Thumbs visible same time (only if thumb is selected)","revslider"); 
_uge("Hide Slider Under Width","revslider"); 
_uge("Hide the slider under some slider width. Works only in Responsive Style. Not available for Fullwidth.","revslider"); 
_uge("Hide Defined Layers Under Width","revslider"); 
_uge("Hide some defined layers in the layer properties under some slider width.","revslider"); 
_uge("Hide All Layers Under Width","revslider"); 
_uge("Hide all layers under some slider width","revslider"); 
_uge("Start With Slide","revslider"); 
_uge("Change it if you want to start from a different slide then 1","revslider"); 
_uge("First Transition Active","revslider"); 
_uge("If active, it will overwrite the first slide transition. Use it when you want a special transition for the first slide only.","revslider"); 
_uge("First Transition Type","revslider"); 
_uge("First slide transition type","revslider"); 
_uge("Replace me!","revslider"); 
_uge("First Transition Duration","revslider"); 
_uge("First slide transition duration (Default:300, min: 100 max 2000)","revslider"); 
_uge("First Transition Slot Amount","revslider"); 
_uge("The number of slots or boxes the slide is divided into. If you use boxfade, over 7 slots can be juggy","revslider"); 
_uge("JQuery No Conflict Mode","revslider"); 
_uge("Turns on / off jquery noconflict mode. You can play with this option when you have some javascript conflicts.","revslider"); 
_uge("Put JS Includes To Body","revslider"); 
_uge("Putting the js to body (in addition to head) is good for fixing some javascript conflicts of type: TypeError: tpj('#rev_slider_1_1').show().revolution is not a function","revslider"); 
_uge("True","revslider"); 
_uge("False","revslider"); 
_uge("Output Filters Protection","revslider"); 
_uge("Activate a protection against wordpress output filters that adds html blocks to the shortcode output like P and BR","revslider"); 
_uge("By Compressing Output","revslider"); 
_uge("By Echo Output","revslider"); 
?>